Leave:
  Message:
    Message: '&7[&c&l-&7] &b%player% &7left the server. This message supports PlaceholderAPI.'
    Enabled: true
  Sound:
    Sound: 'NOTE_BASS'
    Pitch: 1
    Enabled: true
  Commands: []

Server:
  MOTD:
    Options:
      Maintenance: false
      Enabled: true
    List:
      RandomBlue:
        Line-1: '&b&lMinecraft Network &3Now with JoinEventsPro!'
        Line-2: '&3This is a customizable second line of the MOTD.'
      RandomGreen:
        Line-1: '&2&lMinecraft Network &aNow with JoinEventsPro!'
        Line-2: '&aThis is a customizable second line of the MOTD.'
      RandomYellow:
        Line-1: '&e&lMinecraft Network &6Now with JoinEventsPro!'
        Line-2: '&6This is a customizable second line of the MOTD.'
      Maintenance:
        Line-1: '&c&lMinecraft Network &7Now with &eJoinEventsPro!'
        Line-2: '&7This is a customizable second line of the MOTD.'
  Messages:
    Full: '&7[&b&lJOINEVENTSPRO&7] &cThe server is currently full, please check back later.'
    Maintenance: '&7[&b&lJOINEVENTSPRO&7] &cThe server is currently undergoing Maintenance, please check back later.'
  Players:
    Unlimited: true
    Max: 100